FROM node:22-bookworm-slim

WORKDIR /app

# 依存関係定義ファイルのコピー
COPY package.json ./
COPY package-lock.json* ./

# 依存関係のインストール
RUN npm install

# 開発サーバー用のポート
EXPOSE 3000

# 開発サーバーの起動
CMD ["npm", "run", "dev"]
